export const blogPosts = [
  {
    date: "25/09/21",
    id: "d1c1a0d1fe254ad89a469313d2a466b7",
    imageAlt: "alt 1",
    imageId: "about_cphruk",
    tagLine: "",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit eos deserunt ullam quidem? Blanditiis placeat deserunt eum! Illum, perspiciatis debitis!",
    title: "Blog post 1",
    url: "",
  },
  {
    date: "25/09/21",
    id: "9561dab0164043b38d8349c7256024e3",
    imageAlt: "alt 2",
    imageId: "about_cphruk",
    tagLine: "",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit eos deserunt ullam quidem? Blanditiis placeat deserunt eum! Illum, perspiciatis debitis!",
    title: "Blog post 2",
    url: "",
  },
  {
    date: "25/09/21",
    id: "b4d2c04dc4cb4835ab335ecf0ab7467e",
    imageAlt: "alt 3",
    imageId: "about_cphruk",
    tagLine: "",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit eos deserunt ullam quidem? Blanditiis placeat deserunt eum! Illum, perspiciatis debitis!",
    title: "Blog post 3",
    url: "",
  },
  {
    date: "25/09/21",
    id: "0e37a31aa3bc48aea592fcb8a5377f3e",
    imageAlt: "alt 4",
    imageId: "about_cphruk",
    tagLine: "",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit eos deserunt ullam quidem? Blanditiis placeat deserunt eum! Illum, perspiciatis debitis!",
    title: "Blog post 4",
    url: "",
  },
];
