export const projects = [
  {
    date: "25/09/21",
    id: "33e2d2af252e461da3cf5087330723c5",
    imageAlt: "alt 1",
    imageId: "about_cphruk",
    subtitle: "SCSS, REACT, SOMETHING ELSE",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit eos deserunt ullam quidem? Blanditiis placeat deserunt eum! Illum, perspiciatis debitis!",
    title: "Project 1",
    type: "Project",
    url: "",
  },
  {
    date: "25/09/21",
    id: "d0e17a6371ec4e52aebffd32d7008190",
    imageAlt: "alt 1",
    imageId: "about_cphruk",
    subtitle: "SCSS, REACT, SOMETHING ELSE",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit eos deserunt ullam quidem? Blanditiis placeat deserunt eum! Illum, perspiciatis debitis!",
    title: "Project 2",
    type: "Project",
    url: "",
  },
  {
    date: "25/09/21",
    id: "97e4b06295974f81abce1e060b6b4223",
    imageAlt: "alt 1",
    imageId: "about_cphruk",
    subtitle: "SCSS, REACT, SOMETHING ELSE",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit eos deserunt ullam quidem? Blanditiis placeat deserunt eum! Illum, perspiciatis debitis!",
    title: "Project 3",
    type: "Project",
    url: "",
  },
  {
    date: "25/09/21",
    id: "6f8c8c0f60524d29adc3b653c5e09cb6",
    imageAlt: "alt 1",
    imageId: "about_cphruk",
    subtitle: "SCSS, REACT, SOMETHING ELSE",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Impedit eos deserunt ullam quidem? Blanditiis placeat deserunt eum! Illum, perspiciatis debitis!",
    title: "Project 4",
    type: "Project",
    url: "",
  },
];
